### ISSUE TITLE
app.js not prompting for any details

### ISSUE THREAD

**Issue by SeemaSP** [adlnet/xapi-launch#10]
I created a config.json file and then ran the node app.js command.
But even after that, it doesn't prompt for the details and this is all that is on the console:
```

config file incomplete. Please delete this config file and re-start the app to set up.
Using default connection string
Email is not set up in the config file. User accounts need to be verified manually by the admin.

```
And when I try removing the config.json and run node app.js
It gives the following error:
`Error: Cannot find module '../config'
`

**Comment by rchadwic** [comment]
Sorry about that. I've just pushed a fix to the master  branch. Try that?

**Comment by SeemaSP** [comment]
I cloned the new master branch and it worked. Thanks for fixing the issue.
