### ISSUE TITLE
In xapi-launch db in mongo, some collections are missing

### ISSUE THREAD

**Issue by SeemaSP** [adlnet/xapi-launch#12]
I have been going through the ODM dir where you have defined all your models. There I saw the following models registered to mongo:

- contentRecord.js 
- file.js
- launchRecord.js
- media.js
- mediaType.js
- package.js
- userAccount.js

But when I did:
`mongo`
and tried to view the collections of xapi-launch db:
`show dbs`
**outcome:**
xapi-launch
```
use xapi-launch
show collections
```
**outcome:**
contentrecords
launchrecords
useraccounts

I checked the /ODM/schemas .js files and the code to register all models is just fine but still not all models are in the db. I did not get any error during the install to figure out what could have gone wrong.

**Comment by rchadwic** [comment]
I don't actually think this is a problem at all. Mongoose will create those collections only if an object is inserted into them. Unlike SQL, Mongo is super flexible, and does not require that sort of thing to be set up ahead of time.
