### ISSUE TITLE
Issue with port 3000?

### ISSUE THREAD

**Issue by jamesdahingo** [adlnet/xapi-launch#18]
Hi All, 

I'm trying to set this up to a server with Learning Locker installed (centoOS).  LL is already listening to port 3000 so I was thinking this error below is related to it?  If yes, if there a way to edit the app.js to listen to a different port i.e 5000?  Any input will help :)

$ node app.js
Using default connection string
Email is not set up in the config file. User accounts need to be verified manually by the admin.
(node:1816) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:160
      throw er; // Unhandled 'error' event
      ^

  Error: listen EADDRINUSE :::3000
  
  - util.js:1020 Object.exports._errnoException
    util.js:1020:11
  
  - util.js:1043 exports._exceptionWithHostPort
    util.js:1043:20
  
  - net.js:1277 Server._listen2
    net.js:1277:14
  
  - net.js:1313 listen
    net.js:1313:10
  
  - net.js:1409 Server.listen
    net.js:1409:5
  
  - application.js:618 EventEmitter.listen
    [xapi-launch]/[express]/lib/application.js:618:24
  
  - app.js:158 startServer
    /var/tmp/james/xapi-launch/app.js:158:6
  
  - async.js:726 
    [xapi-launch]/[async]/lib/async.js:726:13
  
  - async.js:52 
    [xapi-launch]/[async]/lib/async.js:52:16
  
  - async.js:269 
    [xapi-launch]/[async]/lib/async.js:269:32
  
  - async.js:44 
    [xapi-launch]/[async]/lib/async.js:44:16
  
  - async.js:723 
    [xapi-launch]/[async]/lib/async.js:723:17
  
  - async.js:167 
    [xapi-launch]/[async]/lib/async.js:167:37
  
  - app.js:73 NativeConnection.<anonymous>
    /var/tmp/james/xapi-launch/app.js:73:4
  
  - events.js:292 NativeConnection.g
    events.js:292:16
  
  - events.js:86 emitNone
    events.js:86:13

**Comment by jamesdahingo** [comment]
you may ignore the mongoose error above, I already fixed that

**Comment by vbhayden** [comment]
Do you have anything else running on that port?  Alternatively, have you tried running it on a different port?

**Comment by jamesdahingo** [comment]
I have Learning Locker LRS running on that port that I can't change

**Comment by vbhayden** [comment]
Sounds like that is your problem.  :-)

By default, the launch server is set up to use port 3000.  You can change that at the bottom of `app.js`.  You can set it to something like 3001 and increment the other ports appropriately.  Be sure to change your `config.json` to reflect the new port you're using.

**Comment by vbhayden** [comment]
I am going to close this issue as it was not related to the launch project, but feel free to continue asking questions on configuring your project's port here.

**Comment by jamesdahingo** [comment]
I really appreciate your response, vbhayden!  I haven't tried it again but will go back working on it later today.  Thank you so much! :)

**Comment by jamesdahingo** [comment]
Hi all, 

This is a continuation but not really related to my initial concern.  So I managed to make the app.js run and was able to test launch.  My question is, this might be silly, how do you exactly make this talk to the LRS and my LMS?  Is there an additional service needed to run or a plugin of some sort?

**Comment by FlorianTolk** [comment]
Hello jamesdahingo,

xapi-launch is a server, you need to send some form of a request to the server in order to communicate. I would suggest you take a look [here](https://github.com/adlnet/xAPIWrapper) as this is the wrapper we built for xAPI specifically.
