### ISSUE TITLE
fsevents is Mac only module

### ISSUE THREAD

**Issue by GitPlz** [adlnet/xapi-launch#3]
Server side demo can't be ran on Linux due to fsevents dependency. fsevents is only available for Mac.

https://www.npmjs.com/package/fsevents

**Comment by rchadwic** [comment]
Hummm I'm sure I was able to run it on Windows 10. Where is fsevents used? It's possible that it is part of the template we started from, and not actually used anyway.

**Comment by GitPlz** [comment]
I was wrong, the demo does run, it's just a warning that's given when running npm install:

notsup Not compatible with your operating system or architecture: fsevents@1.0.13

It looks like it's used by the module chokidar

**Comment by rchadwic** [comment]
Yeah, that project started from some template that really is much too thick for what the project does. There are a lot of dependencies that are not needed. We did remove the link to MongoDB, but have not scrubbed out all the other unnecessary stuff.
