### ISSUE TITLE
CERT_UNTRUSTED error

### ISSUE THREAD

**Issue by rneatrour** [adlnet/xapi-launch#6]
When I try to send a statement, I receive the following error in the terminal that is running the launch server: Error posting to the LRS https://lrs.adlnet.gov/xapi/: Error: CERT_UNTRUSTED
And I get this error in the developer tools console in Chrome. http://localhost:8080/xapiwrapper.min.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)a.XHR_request @ xapiwrapper.min.js:2

I resolved the issue by adding process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; at line 597, but I'm not entirely sure how safe this is. 

Out of 3 machines running the same configuration and demo, only one experienced the issue.

**Comment by rchadwic** [comment]
I think this is actually an issue with the OS cert store. I wonder what the root CA is for the *.adlnet cert. It's possible that the root cert is not installed in some way. All same OS? Same Node versions?

**Comment by ljwolford** [comment]
Forgot this was out there...to answer your question Rob, yes they were all the same OS and Node versions

**Comment by rneatrour** [comment]
Updated Node.js to v6.9.5.  No longer receive the CERT_UNTRUSTED error.
